import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

/**
 * SEO Push Script for Baidu and Bing.
 * Uses IndexNow for Bing/Baidu and Baidu's Active Push API.
 * 
 * Usage: node scripts/seo-push.mjs [urls...]
 * If no URLs are provided, it reads from the sitemap-0.xml (generated by Astro).
 */

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = path.resolve(__dirname, '..');

// --- Configuration ---
const SITE_URL = 'https://peterclaw.com';
const BAIDU_TOKEN = process.env.BAIDU_PUSH_TOKEN;
const INDEXNOW_KEY = process.env.INDEXNOW_KEY || 'peterclaw1234567890'; // Placeholder key
const INDEXNOW_KEY_FILE = `${INDEXNOW_KEY}.txt`;

// IndexNow Endpoints
const INDEXNOW_ENDPOINTS = [
  'https://www.bing.com/indexnow',
  'https://ziyuan.baidu.com/indexnow',
];

async function getUrlsFromSitemap() {
  const sitemapPath = path.join(ROOT_DIR, 'dist', 'sitemap-0.xml');
  if (!fs.existsSync(sitemapPath)) {
    console.warn('Sitemap not found at', sitemapPath, '. Run npm run build first.');
    return [];
  }
  const content = fs.readFileSync(sitemapPath, 'utf-8');
  const urls = [...content.matchAll(/<loc>(.*?)<\/loc>/g)].map(m => m[1]);
  return urls;
}

async function pushIndexNow(urls) {
  if (!INDEXNOW_KEY) {
    console.warn('INDEXNOW_KEY not set. Skipping IndexNow.');
    return;
  }

  // Ensure key file exists in public/ (so it's deployed to root)
  const publicDir = path.join(ROOT_DIR, 'public');
  const keyFilePath = path.join(publicDir, INDEXNOW_KEY_FILE);
  if (!fs.existsSync(keyFilePath)) {
    console.log(`Creating IndexNow key file: ${INDEXNOW_KEY_FILE}`);
    fs.writeFileSync(keyFilePath, INDEXNOW_KEY);
  }

  const data = {
    host: new URL(SITE_URL).hostname,
    key: INDEXNOW_KEY,
    keyLocation: `${SITE_URL}/${INDEXNOW_KEY_FILE}`,
    urlList: urls,
  };

  for (const endpoint of INDEXNOW_ENDPOINTS) {
    try {
      console.log(`Pushing to IndexNow endpoint: ${endpoint}`);
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data),
      });
      console.log(`  Response: ${response.status} ${response.statusText}`);
    } catch (err) {
      console.error(`  Error pushing to ${endpoint}:`, err.message);
    }
  }
}

async function pushBaiduActive(urls) {
  if (!BAIDU_TOKEN) {
    console.warn('BAIDU_PUSH_TOKEN not set. Skipping Baidu Active Push.');
    return;
  }

  const endpoint = `http://data.zz.baidu.com/urls?site=${SITE_URL}&token=${BAIDU_TOKEN}`;
  try {
    console.log(`Pushing to Baidu Active Push API...`);
    const response = await fetch(endpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'text/plain' },
      body: urls.join('\n'),
    });
    const result = await response.json();
    console.log(`  Response:`, result);
  } catch (err) {
    console.error(`  Error pushing to Baidu:`, err.message);
  }
}

async function main() {
  let urls = process.argv.slice(2);
  if (urls.length === 0) {
    console.log('No URLs provided, reading from sitemap...');
    urls = await getUrlsFromSitemap();
  }

  if (urls.length === 0) {
    console.log('No URLs to push.');
    return;
  }

  console.log(`Found ${urls.length} URLs to push.`);
  
  await pushIndexNow(urls);
  await pushBaiduActive(urls);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
